package com.menes.dw.model;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;
@Data
@Entity
@Table(name = "currency_exchange_rates")
public class CurrencyExchange {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "currency_code")
    private String currencyCode;

    @Column(name = "currency_name")
    private String currencyName;

    @Column(name = "cash_buying")
    private Double cashBuying;

    @Column(name = "telegraphic_buying")
    private Double telegraphicBuying;

    @Column(name = "selling")
    private Double selling;

    @Column(name = "bank_name")
    private String bankName;

    @Column(name = "publish_date")
    private LocalDate publishDate;

    @Column(name = "publish_time")
    private LocalDateTime publishTime;

    // Constructors are automatically generated by Lombok
    // No need to explicitly define getters, setters, toString, equals, and hashCode
}
